# This is a basic workflow to help you get started with Actions

name: Zafeerah skin clinic development

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  
  ##create:
    ##tags:
      ##- 'v*' # Match any tags starting with 'v'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 deploy:

  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SSH_HOST }}
        username: ${{ secrets.DEV_SSH_USERNAME }}
        password: ${{ secrets.DEV_SSH_PASSWORD }}
        script: |
          cd /home/cruc/public_html/tp/zafeerah-skin-clinic/
          git checkout -f
          git pull 
          composer install --no-cache
          php artisan cache:clear